#!/usr/bin/env python3
"""Apply Italian translations to data/animals.json."""
import json
from pathlib import Path

ROOT = Path(__file__).parent.parent
DATA_FILE = ROOT / "data" / "animals.json"

TRANSLATIONS = {
"aalscholver": "Questo uccello marino si immerge nuotando, procurandosi il pesce con grande abilità. Il cormorano è socievole e nidifica in colonie sulle scogliere o su alberi alti nell'entroterra. Collabora bene ed efficacemente con i suoi simili. Dopo la pesca sembra godersi il sole in piena tranquillità. I cormorani sono silenziosi di natura, ma fanno sentire la loro voce quando sono in gruppo.",
"aap": "La scimmia è intelligente, ma si fa spesso ingannare. Sono molto vivaci ed enormemente agili. Una scimmia è buffa, allegra e coraggiosa. Una scimmia femmina si prende cura della sua prole.",
"aardeekhoorn": "I tamia sono attivi di giorno. Sono buoni arrampicatori, ma preferiscono stare a terra. I tamia costruiscono un complesso sistema di gallerie sotterranee. Sono socievoli, selettivi e abilissimi nel fare scorte di cibo.",
"adder": "La vipera è un serpente tozzo con scaglie dure, resistente alla vita in climi freddi. Hanno un territorio fisso e vivono in solitario. Le vipere sono cacciatrici inventive e molto efficienti. Non sono aggressive, ma in caso di pericolo possono sembrare minacciose.",
"agame": "Questa lucertola è una gran mangiona. Sono divertenti, birichini, curiosi e provocatori. L'agama si adatta con facilità. Sono molto veloci, a volte bizzarri, ma innocui. L'agama adora il sole e il calore e intimida i nemici con fanfaronate.",
"agoeti": "Questi slanciati roditori sono divertenti e laboriosi. Sono instancabili. Monelli sfacciati e per nulla timorosi. Tra i propri simili, l'aguti può talvolta essere intollerante.",
"albatros": "L'albatro è un magnifico, maestoso e robusto uccello marino. Si muove con grazia e sembra non aver bisogno di riposo. Una combinazione di perseveranza, resistenza e un intelligente uso del vento permette loro di percorrere grandi distanze. L'albatro è un animale fedele che nidifica in grandi colonie.",
"alk": "Questi uccelli marini dalla testa nera nuotano e si immergono con facilità. L'alca preferisce un volo breve, perché in aria appare un po' goffa. Le alche vivono e nidificano in grandi gruppi e si prendono cura dei propri piccoli.",
"alpaca": "Gli alpaca sono animali testardi e fieri. Quando si mettono in testa qualcosa, non c'è verso di farli cambiare idea e persistono ostinatamente. Un alpaca è selettivo riguardo al cibo. Vivono in buona armonia con i propri simili.",
"alpenhond": "Questi cani selvatici hanno una grande capacità di adattamento. Sono snelli, veloci e dotati di grande resistenza. In particolare l'olfatto e l'udito sono molto sviluppati. Conducono una vita comunitaria unita e sono molto sociali, ma possono reagire con veemenza verso gli estranei.",
"amerikaanse-zeearend": "L'aquila di mare americana si nutre principalmente di pesce. Questo uccello è molto flessibile e adatta i metodi di caccia alle circostanze. Possono restare immobili per lungo tempo, senza che nessun movimento nell'ambiente circostante sfugga loro. Sono fedeli ai loro partner e molto legate al nido.",
"anaconda": "Questo gigantesco serpente acquatico trascorre la maggior parte del tempo in un fiume e si nutre di animali terrestri che vengono ad abbeverarsi. Dopo mangiato, si gode soddisfatto il sole. L'anaconda è unica e molto sensibile alle vibrazioni del suolo e dell'acqua. Questo serpente è veloce e astuto, ma anche cauto.",
"anemoonvis": "Questo famoso pesce ama la sicurezza della barriera corallina. Il suo aspetto allegro sa come affascinare chiunque. Il pesce pagliaccio dà molta importanza all'ambiente circostante e prospera in gruppo. È premuroso verso la prole e i propri simili. In acque calde è intelligente, energico e versatile. Quando sfidato, reagisce con astuzia e senza pietà.",
"ani": "Questo cuculo è tra gli uccelli più insoliti al mondo. L'ani è straordinariamente sociale e vive in gruppi che si comportano come una famiglia unita. Rimangono sempre vicini al gruppo. Collaborano per difendere il loro territorio comune. Se uno degli uccelli è ferito, gli altri lo proteggono con compassione.",
"antilope": "L'antilope è un grande cervide che vive in gruppo. Le antilopi sono pazienti, snelle, caute ed eleganti. I loro sensi sono molto sviluppati, così che notano tutto. Vivono in pace con altri animali affini, sono vivaci, agili e graziose. Sono intelligenti e imparano dall'esperienza.",
"ara": "Rispetto agli altri pappagalli, le are sono tranquille e serie. Si abituano rapidamente a un nuovo ambiente e sono docili e fedeli se trattate bene. Questo uccello intelligente è curioso per natura. L'ara va d'accordo con i propri simili ma può essere scontrosa con gli estranei.",
"arapaima": "Questo intelligente animale sociale scava un nido nella sabbia per i suoi piccoli, che protegge a lungo. L'arapaima si mostra amichevole e disponibile in compagnia di fiducia, ma non evita i confronti. In un momento può aggirarsi allegramente e impetuosamente, per poi reagire con slancio. Regolarmente nuota in superficie per respirare. Anche gli uccelli fanno parte della sua preda. L'arapaima è sempre pronto per la prossima sfida.",
"arassari": "Questo piccolo tucano è un impertinente buffone. Sembra trasandato, ma non lo è. Sono allegri e vivaci. Essere sempre occupati è la loro ragione di vita. Gli araçari sono veri giocherelloni, dispettosi e non immediatamente appariscenti. Vivono in stormi. In caso di pericolo non fuggono, ma aiutano i propri simili.",
"arend": "Questi imponenti e regali rapaci sono coraggiosi e astuti. Hanno una pazienza infinita. Un'aquila è ben sviluppata, sia fisicamente che mentalmente. Hanno un carattere fiero e calmo. È sensibile e mostra sempre chiaramente il suo malcontento. Persevera testardamente in un piano una volta concepito. Nemmeno l'opposizione la distoglie dai suoi propositi. Un'aquila è curiosa di imparare, fiera e dignitosa.",
"axolotl": "L'axolotl vive appartato nei laghi profondi. Questa salamandra è dolce e resiliente. Al primo contatto rimane vigile e schivo. Con un'acuta capacità di osservazione, questo cacciatore ingegnoso si adatta senza sforzo all'ambiente. L'axolotl appare gioviale, ma può improvvisamente diventare giocoso ed energico.",
"baardkoekoek": "Questo uccello ha un piumaggio morbido e soffice. Sono pazienti, ma anche temerari. Il cuculo barbuto sta immobile a lungo finché una preda non passa, e poi reagisce rapidamente e abilmente. Nulla gli sfugge. Sono fedeli al loro posto d'osservazione: se qualcosa li spaventa, non volano mai lontano da esso.",
"banteng": "Questo ungulato selvatico è di colore marrone rossastro o marrone scuro con corna ricurve verso l'alto. Il banteng è un arrampicatore forte e tenace. Sono robusti, sicuri di sé e sempre in guardia. Hanno una grande resistenza e vivono in greggi. Un banteng è versatile e utile.",
"barracuda": "La barracuda è un predatore forte e coraggioso che in alcuni luoghi è più temuto degli squali. Chi la conosce bene sa tuttavia che ciò è ingiusto. Collabora tatticamente e attivamente in grandi banchi. I giovani sono resilienti e autosufficienti. La barracuda può mostrarsi opportunista.",
"baviaan": "Questa scimmia terrestre è robusta e vive in gruppi uniti dove vige una rigida gerarchia. Il babbuino è premuroso, coraggioso e ha una grande capacità di adattamento. Possono talvolta reagire impetuosamente. Un babbuino è previdente e un bravo imitatore.",
"beensnoek": "Questo grande pesce d'acqua dolce predilige acque tranquille e poco profonde. Nonostante sia un pesce predatore, il luccio armato è pacifico per natura e non aggressivo. Vivono in piccoli gruppi. È opportunista e un attento esploratore. Sa godersi l'immobilità nell'acqua come pochi, ma anche essere velocissimo.",
"beer": "Un orso è un animale grande e forte. Non sono particolarmente veloci, ma compensano con una fantastica resistenza. Nuotano e si arrampicano con destrezza. Un orso è intelligente e ha una grande capacità di adattamento e talento nell'improvvisare. Sono bonari e socievoli, ma anche imprevedibili, il che li può rendere pericolosi.",
"beerdiertje": "Il tardigrado è noto come l'animale più resiliente della terra. È perseverante, forte e coraggioso. Vitale e ingegnoso, si adatta e sopravvive in tutte le circostanze. Guidato dalle correnti, questo minuscolo essere mostra una sorprendente quantità di coraggio. Ama collaborare, ma può anche trovare la propria strada vagabondando.",
"beermarter": "Il binturong ha una coda prensile muscolosa unica. Fedele e docile è il loro carattere. Un binturong conduce una vita tranquilla e pacifica. Quando sono attivi, fanno sentire la loro presenza. Sono dolci e gentili e sembrano voler bene a tutti. È calmo e giocoso, ma può talvolta essere aggressivo se messo alle strette.",
"beloega": "Questo delfino bianco ha un corpo possente con una piccola testa arrotondata. Un beluga è comunicativo e talvolta rumoroso. Sono buoni nuotatori con grande resistenza. Un beluga vive in gruppo e conduce un'esistenza nomade. Questo delfino è veloce e giocoso.",
"beo": "Questo buffo uccello parlante si sente a suo agio in ogni ambiente. Vivono in piccoli gruppi. Un myna è curioso, molto attivo, chiassoso, ma a volte anche timido. Sono affettuosi, amichevoli e sempre pronti ad interessarsi a tutto. Il myna è un bravo imitatore.",
"bergbever": "Questo roditore attivo non si avventura mai lontano dalla sua tana. Uno scoiattolo di montagna è ordinato e diligente. Tollerano quasi tutti gli animali nel loro territorio, purché non abbiano cattive intenzioni. Quando incontra difficoltà, è tenace e inventivo. Raramente si arrendono prima di trovare una soluzione. In un ambiente familiare è tranquillo.",
"berglemming": "Questo piccolo roditore vive sulla tundra e nei pascoli montani. Il lemming di montagna è robusto e attivo sia di giorno che di notte. In caso di pericolo non abbandona i propri simili. Sono sociali e si adattano con facilità. Il lemming di montagna è avventuroso e un po' temerario.",
"berner-sennenhond": "Il bovaro del Bernese è un cane da montagna grande e robusto. Amano stare all'aperto e girano volentieri liberi. Questo cane è desideroso di imparare, obbediente, vigile e attento. È mite, tollerante e si adatta facilmente. Sono indipendenti, ma per questo a volte un po' testardi. Il bovaro del Bernese ha un buon carattere. Con i conoscenti è affettuoso.",
"bever": "Il castoro è un roditore laborioso, previdente e prudente. Questo bravo nuotatore e sommozzatore vive in colonie. Si oppongono alla costrizione. Il castoro è sociale, ma piuttosto silenzioso e ha pochi nemici. Sono ingegnosi e hanno un'enorme voglia di costruire. Un castoro è fedele e rimane con il proprio partner per tutta la vita.",
"bij": "L'ape è un insetto sociale. Lavora sodo ed è sempre indaffarata. Le api hanno una chiara divisione dei compiti. L'ape impara rapidamente osservando gli anziani e impara facendo. È altruista. Qualunque cosa faccia, è sempre orientata al benessere degli altri. Un'ape è orientata al futuro.",
"bizon": "Il bisonte è bonario e timoroso. Questo animale sociale diventa irrequieto e imprudente quando qualcosa o qualcuno lo irrita. Il bisonte vive in mandrie con una chiara gerarchia. In queste mandrie i più deboli vengono protetti. Il bisonte è ricettivo all'amicizia e ama imparare.",
"bladschaap": "La lumaca di mare ha numerose piccole protuberanze simili a foglie, che la fanno sembrare una pecora lanosa. Mangia le cellule verdi delle alghe, il che gli permette anche di fare la fotosintesi. Ottiene energia prendendo il sole e produce luce propria nel buio, motivo per cui gli altri la lasciano in pace. Si muove lentamente e con cautela. Grazie al colore verde o marrone, può facilmente nascondersi tra le alghe marine e i coralli e mangiare indisturbata tutto il giorno.",
"blauwe-reiger": "Questo uccello ha un lungo becco robusto e una banda nera attraverso l'occhio che si prolunga nel ciuffo. Sono cauti e piuttosto schivi. L'airone cenerino è molto paziente e non selettivo. I suoi movimenti sono eleganti, tranquilli, lenti e riflessivi. Vive in colonie durante la stagione riproduttiva, ma per lo più in piccoli gruppi o da solo durante il resto dell'anno.",
"blauwe-vinvis": "Questo mammifero marino è il più grande animale che vive sulla terra. Nonostante le sue dimensioni, ha un aspetto elegante. La balenottera azzurra è tenace e percorre migrazioni di migliaia di chilometri. Sono pacifiche e non hanno predatori naturali. Vive spesso da sola, ma anche in coppie o piccoli gruppi e talvolta in grandi gruppi. Sono molto comunicative e famose per il loro canto.",
"blauwe-zeeslak": "Il drago blu è un abitante unico degli oceani tropicali. Sono docili e si lasciano trasportare dalla corrente. Quando raggiunge il suo obiettivo, si avvicina tranquillamente. Il drago blu è curioso e impara facendo cose nuove. Sono selettivi e versatili.",
"boomkikker": "Negli arbusti vicino a uno stagno si nasconde questo gaudente casalingo. La raganella è estremamente espressiva e cambia colore dal verde scuro al marrone quando non si sente bene. Questo buffo anfibio è un buon ascoltatore che mostra interesse per gli altri. La raganella è molto comunicativa e trova sempre un motivo per ridere.",
"boomklever": "Questo uccello non fa del male a nessuno e non ha nemici. Spesso si fa sentire prima di vedersi. Il picchio muratore è attivo e sempre indaffarato. A volte può avere momenti di testardaggine nei momenti più inopportuni, ma in generale è socievole. Preferisce i piccoli gruppi.",
"bosbok": "Questa piccola antilope ha sensi molto sviluppati e riesce a compiere salti enormi. Vivono soli, in coppia o in piccoli gruppi familiari. L'antilope boschiva è attiva e si adatta bene alle circostanze mutevoli. Sono tolleranti verso i propri simili. È un po' timida, ma anche coraggiosa. Poiché offre una strenua resistenza, gli aggressori non trovano in essa una preda facile.",
"bosduiker": "Questa piccola antilope è un animale veloce e schivo che si tuffa nel bosco al minimo pericolo. Sa muoversi velocemente e agilmente tra gli ostacoli. Ha un forte istinto di sopravvivenza, anche nei momenti difficili sa cavarsela. Una coppia condivide tutto e raramente si allontana l'uno dall'altro. È legata al proprio territorio e preferisce restare nella propria zona di comfort.",
"boxer": "Questo cane è allegro, bonario e schietto. Il boxer è fedele e piacevole. Sono facili da addestrare. Il boxer è molto vivace e ha un carattere giocoso. Vegliano rigorosamente sul loro territorio e sono animali coraggiosi.",
"bruinvis": "La focena non è né marrone né un pesce. Questo nuotatore energetico vive coraggiosamente e senza timore vicino alle foci dei fiumi e alle zone costiere. La focena è un animale sociale. Si mostra amichevole e tollerante sia con i propri simili che con gli altri. Grazie ai loro denti a forma di spatola, cattura con grande facilità piccoli pesci. Questo intelligente sommozzatore ama esplorare terreni sconosciuti. Grazie al forte senso dell'orientamento e alla memoria, trova sempre la strada verso i suoi rifugi estivi e invernali.",
"brulaap": "Quando la scimmia urlatrice si sveglia al mattino, segna solitamente il suo territorio con il caratteristico urlo. Questa scimmia vive in gruppo e si muove lentamente e tranquillamente, tranne quando gioca o è eccitata. La scimmia urlatrice non ha quasi nessun nemico. Sono talvolta suscettibili ma anche sorprendentemente sensibili, bravi e dolci.",
"buffel": "Questo animale domestico è di natura socievole, ma spesso viene giudicato male. Il bufalo è raramente rumoroso. Vivono in stretto legame con il resto del branco. Il bufalo è molto premuroso e collabora bene. I bufali difendono gli altri membri del gruppo quando sono in pericolo. Un branco non ha una vera guida. I bufali decidono insieme o a turno dove andare.",
"bunzing": "La puzzola è agile, veloce e astuta. Ed anche: prudente, perspicace e coraggiosa. La puzzola è indifferente al dolore o al disagio e sa adattarsi bene al proprio ambiente. Sono attive soprattutto di notte. La puzzola è previdente: fa scorte di cibo.",
"chimpansee": "Lo scimpanzé è una grande e forte scimmia antropomorfa. Come tutte le scimmie è da definirsi intelligente eppure si lascia ingannare in modo sciocco. Sono i mammiferi più vivaci e agili, buffoni e allegri. Lo scimpanzé è coraggioso e la madre si prende cura dei suoi piccoli.",
"collie": "Il collie è un cane da pastore discendente dalle pecore britanniche e scozzesi. Sono fedeli, intelligenti e simpatici. I collie sono utili come cani da lavoro, ma anche come animali domestici. Sono gioviali ma possono anche essere gelosi. Imparano in fretta e hanno una buona memoria.",
"dingo": "Questo cane selvatico australiano non abbaia, ma comunica attraverso un ululato simile a quello del lupo. Il dingo è intelligente, molto indipendente e quindi difficile da addomesticare. Vivono in piccole famiglie unite. Sono veri perseveranti nella caccia. Il dingo è alternativamente attivo e tranquillo.",
"dolfijn": "Il delfino è socievole, sbarazzino, allegro e molto vivace. È un bravo imitatore, dispettoso ma amichevole. Per le linee curve del suo muso, un delfino sembra sempre sorridere.",
"duif": "La colomba è elegante nei movimenti. Questo uccello amichevole ha un portamento aggraziato. Volano veloci e hanno grande resistenza e un forte senso dell'orientamento. La colomba mette poca energia nella costruzione del nido ed è quindi facilmente soddisfatta.",
"eekhoorn": "Lo scoiattolo è un roditore astuto, furbo e velocissimo. Da giovane è allegro e vivace. Amano essere accarezzati. Sono sempre indaffarati e sempre consapevoli delle proprie capacità. Lo scoiattolo è noto soprattutto come acrobata provetto che salta con grazia da un albero all'altro. Di solito reagiscono in modo sfidante a un intruso, dopodiché spariscono dietro un albero o un ramo.",
"egel": "Il riccio va in cerca di cibo soprattutto di notte. Non sono esigenti, sono laboriosi, attenti e vigili. Il riccio non è territoriale e tollera i propri simili nel suo territorio. Assume rapidamente una posizione difensiva quando si prospetta un pericolo.",
"ekster": "La gazza è famosa per nascondere oggetti luccicanti. Sono sicure di sé, intelligenti e molto curiose. Quando si accorge di essere accettata, la gazza diventa rapidamente amichevole e talvolta invadente. Hanno un forte senso di comunità. Questo uccello utile è spesso molto eccitato. La gazza chiacchiera incessantemente con una sorprendente ricchezza di suoni.",
"emoe": "Questo uccello australiano non sa volare. Percorrono intere regioni e sono molto attivi. Nelle calde giornate estive, l'emù è spesso l'unico animale attivo. Grazie alla loro grande resistenza, possono camminare per lungo tempo. Quando necessario, possono anche raggiungere una velocità esplosiva. L'emù è molto curioso e raramente aggressivo.",
"ezel": "L'asino è spesso associato alla stupidità, ma ciò è ingiusto. Sono particolarmente intelligenti e prudenti. L'asino è caparbio: non fa nulla che non voglia fare. Ma una volta guadagnata la loro fiducia, è amichevole e docile e talvolta stringe amicizie per la vita. L'asino ama rendersi utile. Sono molto forti e hanno una buona resistenza. Vivono in gruppo e sono spesso molto attivi e vivaci.",
"fennek": "Il fennec è una piccola volpe con grandi orecchie. Vivono principalmente nei deserti. Il fennec è astuto, attento e ha sensi molto sensibili. Questo animale che vive nelle tane esce principalmente di notte. Il fennec è molto attivo e giocoso.",
"flamingo": "Questo uccello appariscente sembra fragile e delicato, ma sopravvive bene anche nelle condizioni più difficili. Sono sociali e vivono in grandi comunità. La comparsa di un intruso è sufficiente a creare agitazione nell'intera colonia. Il fenicottero è sensibile. Sono riconoscibili per il loro continuo e buffo gracchiare.",
"gazelle": "La gazzella è intelligente, molto veloce, vivace, agile e graziosa. Sono sveglie, astute e molto prudenti. La gazzella è graziosa e vive in pace con altri animali affini. Possono raggiungere alte velocità, ma lo fanno raramente, solo per sfuggire a un aggressore.",
"gier": "L'avvoltoio ha un'apertura alare enorme e sembra volare lentamente. Sono sociali e poco prudenti. Questo uccello è socievole e collabora bene per trovare cibo. L'avvoltoio condivide il cibo con i propri simili. Hanno grande resistenza, perseveranza e una pazienza infinita. L'avvoltoio vive in gruppi con una rigida disciplina e gerarchia.",
"giraf": "La giraffa è sveglia e intelligente. Si muove con grazia e dolcezza. Nonostante le sue dimensioni è mite e pacifica. Solo quando viene importunata, la giraffa si difende con le sue potenti zampe muscolose.",
"gnoe": "Lo gnu è un bufalo impetuoso e allegro con il senso dell'umorismo. Fanno salti sfrenati e mostrano la loro combattività scavando con i garretti nella terra. Lo gnu è un animale da branco che percorre grandi distanze. Sono fieri e temperamentali. Se si spaventa, scappa all'improvviso.",
"gorilla": "Il gorilla è una grande e imponente scimmia antropomorfa. Sono piuttosto schivi, nonostante il loro aspetto intimidatorio. Il gorilla è intelligente, ma tarda a diventare indipendente. Questa scimmia ha un aspetto espressivo, non è molto combattiva ed è pacifica. Il gorilla vive in piccole famiglie.",
"grizzlybeer": "L'orso grizzly è un imponente orso dal muso lungo. Questo eccellente nuotatore ama vivere da solo. Sono attivi, ma si godono anche un lungo letargo invernale. L'orso grizzly è intelligente, curioso e giocoso. Sono bonari e socievoli, ma rimangono imprevedibili e possono quindi essere pericolosi.",
"haai": "Questo pesce predatore è un nuotatore veloce. Lo squalo supera la preda e poi si gira improvvisamente per attaccare meglio e di sorpresa. Hanno sensi potenti e sono curiosi, attenti e giocosi. Lo squalo ha una personalità marcata. Solo poche specie di squali sono pericolose.",
"hamster": "L'aspetto buffo del criceto può essere ingannevole, perché ha un comportamento territoriale. Sono energici e curiosi. Un criceto diventa rapidamente indipendente e vive in solitario. Sono ordinati e amano l'ordine. Il criceto fa grandi scorte. Sono quindi previdenti e ben organizzati.",
"havik": "L'astore è un rapace di medie dimensioni che continua a mantenere il suo nido per anni. Questo uccello è un po' riservato e attaccato al territorio. L'astore evita gli ostacoli sul suo percorso come nessun altro. Coraggioso, potente e straordinariamente veloce sono le sue caratteristiche. L'astore è ardente e impetuoso.",
"hermelijn": "Questo animale slanciato ha una bellissima pelliccia. Sanno quello che vogliono e raggiungeranno il loro obiettivo in ogni caso. L'ermellino è agile, veloce, orientato alla famiglia e amante della libertà.",
"hyena": "L'iena vive e caccia in grandi gruppi. Sono silenziose, ma hanno una caratteristica risata. L'iena è cauta, affettuosa e fedele, ma anche astuta e spietata. Hanno una grande resistenza e sono forti.",
"ijsbeer": "L'orso polare vaga da solo o in piccoli gruppi familiari. Quando vive in gruppo, è abbastanza tollerante verso gli altri. Nuotano ottimamente ma lentamente e sono attivi sia di giorno che di notte. L'orso polare è generalmente innocuo, ma è imprevedibile quando ha fame. È un cacciatore opportunista.",
"impala": "Questa specie di antilope vive nelle pianure aperte e nelle aree leggermente boschive, in prossimità dell'acqua. L'impala ha un'eleganza naturale. Sono snelle, agili e flessibili. E anche equilibrate e dolci. L'impala ha buoni sensi. Sono veloci e cauti e vivono in branchi.",
"jaguar": "Questo predatore è il più forte dei felini. Niente ferma un giaguaro. Quando caccia, è estremamente cauto e paziente. Sono forti e hanno sensi molto sviluppati. Il giaguaro non è selettivo ed è flessibile: se non trova preda, si sposta. Sono previdenti: a volte nascondono la preda per dopo. Il giaguaro ama l'acqua ed è un buon nuotatore.",
"jakhals": "Lo sciacallo è un canide snello dall'atteggiamento elegante. Vivono in gruppo e hanno una buona vita comunitaria. Sono veloci e vivaci e attivi soprattutto di notte. Lo sciacallo ha una grande resistenza e non è selettivo nel mangiare.",
"kameleon": "Questa lucertola è molto riflessiva. I loro occhi si muovono indipendentemente l'uno dall'altro. Con il cambio di colore della pelle – un'ottima mimetizzazione – esprime anche il suo umore. Il camaleonte è bonario, calmo e lento, ma a volte può reagire in modo esplosivo.",
"kangoeroe": "Il canguro è un animale straordinario. Sono sociali e di solito si affezionano a una sola persona. Sono protettivi verso la famiglia e i più deboli del gruppo. Al minimo rumore il canguro reagisce con paura o al contrario in modo spericolato. Hanno una grande capacità di adattamento.",
"karper": "Questo noto pesce ha due barbigli sotto il becco. Amano vagare, ma sono comunque attaccati al territorio. In inverno la carpa torna in acque profonde, dove sverna in grandi banchi. È un vero animale da gruppo. La carpa è robusta e tenace. Alcune carpe si seppelliscono per sopravvivere.",
"kat": "Il gatto è di natura indipendente e torna allo stato selvatico rapidamente. Sono autonomi e amanti della libertà. Il gatto si avvicina furtivamente a una preda con infinita pazienza. Questo gaudente è vivace e giocoso.",
"kiwi": "Questo uccello corridore corre e salta velocissimo, ma non sa volare. È un animale cauto e silenzioso. Un kiwi può reagire con veemenza agli intrusi. Ha un olfatto eccellente, cosa unica per gli uccelli. Un kiwi ha un senso del tatto eccezionale sulla punta del becco. Questo uccello notturno vive in coppie ed è fedele.",
"koala": "Questo marsupiale è tranquillo. Il koala si prende cura dei propri piccoli. Sono divertenti, tolleranti e affettuosi. Il koala si affeziona facilmente.",
"kraanvogel": "Questo uccello dal movimento elegante con zampe molto lunghe migra ogni anno avanti e indietro tra la zona di nidificazione e il rifugio invernale. La gru è amichevole, socievole e perspicace. Mostra molto affetto verso i propri simili. È attiva e cammina per lo più con calma e tranquillità. La gru è cauta e selettiva riguardo alla compagnia.",
"krokodil": "Il coccodrillo esce dall'acqua solo per godersi il sole e sembra avere un sorriso costante sul muso. Sono molto potenti e tenaci. Il coccodrillo è molto veloce su brevi distanze sia in terra che in acqua. Come cacciatore ha riflessi rapidi e una buona visione notturna. Il coccodrillo è tenace.",
"leeuw": "Questo cosiddetto re degli animali è uno dei predatori più forti e coraggiosi. Comunicano con vari suoni e il loro ruggito è imponente. Il leone è sociale, fiero e nobile. Predano solo in caso di necessità e possono essere pigri.",
"luiaard": "Questo mammifero notturno di media grandezza si arrampica e pende dagli alberi per la maggior parte del tempo e scende a terra raramente. I bradipi preferiscono stare soli e vanno presto per la propria strada. Il bradipo è cauto, calmo e tranquillo e se la cava bene. Questo animale è tattico nell'ingannare i predatori.",
"luipaard": "Questo magnifico e potente predatore è agile e veloce. È un buon nuotatore e arrampicatore. Il leopardo trascorre la giornata prendendo il sole e riposando. Di notte si avventura cautamente e molto vigile a caccia. Il leopardo sa nascondersi bene. Questo animale è intelligente e coraggioso.",
"lynx": "Questo gatto dalla corporatura robusta ha evidenti basette e una coda corta e spessa molto appariscente. Di giorno ama prendere il sole. La lince è una buona combattente. È forte, arcigna, vigile e di solito vive sola. Poiché cacciano soprattutto di notte, le linci hanno occhi acuti. La lince corre raramente, ma è un camminatore instancabile.",
"maki": "Questo proscimmio è agile, abile e veloce. Il maki vive in gruppo ed è alternativamente attivo e tranquillo. A volte è testardo. Il maki dà un'impressione piacevole ed è di solito mite, premuroso e pacifico.",
"miereneter": "I formichieri sono notevoli per il loro lungo muso. Questo vagabondo è un buon arrampicatore e nuotatore. Nonostante la sua andatura strascicata, è attivo e un cercatore instancabile. In caso di pericolo si difende con veemenza. È affezionato al proprio territorio familiare.",
"mol": "La talpa è uno scavatore sotterraneo. Questo animale ha un udito eccellente e un buon olfatto e senso del tatto. La talpa è irrequieta e non si arrende facilmente. Le talpe diventano rapidamente indipendenti e vivono secondo un programma fisso. Con la loro laboriosità sono capaci di molto. Hanno un buon senso dell'orientamento. La talpa è molto legata al proprio posto e non ama condividerlo.",
"neushoorn": "Questo grande ungulato è agile e veloce, ma ha una resistenza limitata. Il rinoceronte è attivo sia di giorno che di notte, ma si prende di tanto in tanto una pausa di cui gode molto. Questo animale è vigile e ha un buon olfatto e un buon udito. Il rinoceronte è orientato alla difesa. Vive secondo principi fissi, è fedele e si trova bene in piccoli gruppi.",
"nijlpaard": "Con le sue enormi dimensioni e la grande bocca, l'ippopotamo è un animale unico e imponente. Ama prendere il sole in acqua, unendo così l'utile al dilettevole. Questo animale è spensierato, ama stare in compagnia e si prende cura della propria prole. L'ippopotamo sembra pigro, ma sulla terraferma può correre velocemente ed è molto agile. Seguono sempre gli stessi percorsi e il loro passaggio non passa mai inosservato.",
"octopus": "Questo intelligente e versatile abitante del mare si adatta senza sforzo all'ambiente circostante. Sebbene il polpo preferisca stare solo, mostra giocosità nell'interazione con oggetti o prede. Con i suoi tentacoli flessibili si muove sia elegantemente che sorprendentemente veloce. Il polpo fa un'impressione affascinante, ma può talvolta sembrare goffo.",
"oehoe": "Questo grande gufo deve il suo nome al suo verso. Per il loro aspetto imponente hanno pochi nemici. Il gufo reale è vigile e se sente pericolo, cercherà un posto tranquillo altrove. Può stare immobile per ore e poi scattare improvvisamente in azione. È un cacciatore opportunista e previdente. I gufi reali difendono i loro piccoli tenacemente e una coppia rimane insieme per tutta la vita.",
"okapi": "Questo animale raro e straordinario ha un corpo marrone con strisce nere e bianche sulle zampe e sul dorso. L'okapi è sveglio e intelligente e straordinariamente grazioso. Nonostante le sue dimensioni è mite e pacifico. Solo quando viene importunato, si difende con le sue potenti zampe muscolose.",
"olifant": "L'elefante è il più grande e pesante animale terrestre. Vive in mandrie dove vale la legge del più forte. Un elefante è docile, disponibile, curioso di imparare, laborioso, intelligente e vigile. Gli elefanti non sono aggressivi, a meno che non li si faccia arrabbiare. Sono forti e hanno sensi molto sviluppati. Fanno movimenti espressivi con la proboscide. Un elefante è mite, paziente e ha una buona memoria.",
"ooievaar": "Questo elegante uccello ama la compagnia. La cicogna vola generalmente in gruppo su grandi distanze. Il legame di gruppo viene mantenuto attraverso comportamenti altruistici. Tuttavia, la cicogna ha anche bisogno di tempo per sé stessa. I piccoli vengono allevati in un nido ben curato. Le cicogne sono pazienti e hanno una reazione rapida. Esprimono il loro umore con il crepitare del becco.",
"orang-oetan": "Orang-utan significa letteralmente 'uomo della foresta'. Questo animale è sensibile e mite. L'orango diventa rapidamente indipendente. È di buon umore, giocoso, curioso e amante della compagnia. A terra appare goffo. L'orango ha uno sguardo misterioso e mantiene sempre una calma dignità.",
"otter": "Questo maestro nuotatore e sommozzatore ha sensi molto sviluppati. Una lontra è coraggiosa, allegra, forte e intelligente. In generale non è selettiva. La lontra è bonaria. Questo agile vagabondo sa camuffarsi bene.",
"panda": "Il panda è molto raro e perciò non molto conosciuto. Vivono in zone inaccessibili. Il panda è per natura giocoso e ha un aspetto insolito. Questo animale è spontaneo, allegro, agile e affettuoso. Si adatta rapidamente e rimane di buon umore.",
"pauw": "Il pavone è un uccello magnifico. I pavoni sono molto curiosi e hanno una buona memoria. Sono rumorosi e li si riconosce da lontano per il loro richiamo. Il pavone è molto appassionato. Questo vivace ostentatore è fiero e conduce una vita regolare in piccole famiglie.",
"pinguïn": "Questi uccelli usano le ali per fendere l'acqua, come altri uccelli volano nell'aria. I pinguini sono vivaci, socievoli, rumorosi, ingenui e sociali. Il pinguino è straordinariamente abile. Quando cova, è diligente e dedito. Il pinguino conduce una vita regolare.",
"poema": "Questo grande e potente felino si muove con grazia e grande facilità. Vive per lo più in solitario, ma è tollerante e non aggressivo verso i propri simili. I puma mostrano il loro coraggio in caso di pericolo. Hanno una grande vitalità. Anche quando i puma sono mortalmente feriti, continuano a combattere furiosamente. Il puma è previdente.",
"python": "Questo grande serpente costrittore è molto sensibile alle vibrazioni del suolo. Il pitone è veloce e un buon arrampicatore, nuotatore e sommozzatore. È tranquillo, silenzioso e piuttosto passivo, ma può anche essere vivace. Il pitone agisce con riflessione e caccia tramite agguati. I pitoni difendono il proprio nido combattivamente e divorano la preda con avidità.",
"raaf": "Il corvo è il più grande e potente dei corvidi. Sono forti, astuti e abili. Compiono trucchi divertenti e stravaganti. Il corvo è intelligente e impara facilmente. Questo uccello mangia per lo più carogne e accumula cibo.",
"rendier": "La renna è sveglia e ha un bell'aspetto. È utile e piuttosto silenziosa. Questo tenace migratore ha una grande resistenza. Le renne vivono in mandrie e trovano la strada ovunque.",
"schildpad": "Le tartarughe possono percorrere distanze considerevoli nonostante il loro pesante guscio. La tartaruga è robusta, tenace e capace di far fronte a molte situazioni. Questo animale è giocoso, ma trascorre la maggior parte della giornata a riposare. Quando però entra in azione, la tartaruga è una temibile avversaria. La tartaruga è intelligente e ha una buona memoria. Sono attente grazie alla loro buona vista e olfatto.",
"schoenbekooievaar": "Il becco a scarpa è un animale straordinario. Vivono in silenzio e solitudine, a volte in piccoli gruppi in zone inaccessibili a molti animali. Il becco a scarpa ha un'eccezionale resistenza e perseveranza. Sono animali intelligenti. Sono sempre pronti a reagire al pericolo: la prudenza è la loro seconda natura. Una volta che il becco a scarpa ha stretto amicizia, è molto fedele.",
"sifaka": "Il sifaka è un grande proscimmio che vive in Madagascar. Vivono in gruppi familiari e sono molto protettivi verso i propri simili. Sono amichevoli, pacifici e sensibili. Sono anche birichini ed entusiasti. Sono intelligenti e riflessivi.",
"sperwer": "Questo rapace ha un occhio giallo molto appariscente. Lo sparviero è coraggioso e a volte sfrontato. Scherzando, spaventa gli altri con un attacco a sorpresa. Lo sparviero è potente, perseverante e ha una grande capacità di concentrazione. Gli sparvieri costruiscono il nido in modo disordinato. Si prendono cura dei loro piccoli con pazienza e vigilanza.",
"springbok": "Lo springbok vive in grandi gruppi con una forte struttura sociale. Sono miti, curiosi, tranquilli, vigili, intelligenti e amichevoli. Lo springbok vive in pace con gli altri. Il loro nome si riferisce al salto che fanno per avvertire il branco del pericolo imminente. Lo springbok raramente sceglie lo scontro. Non abbandonano i propri simili.",
"stekelvarken": "Questo roditore è un piccolo e silenzioso animale notturno che di giorno se ne sta a prendere il sole davanti alla tana. L'istrice è tenace e difficile da convincere, a volte un po' testardo. Finché non si sente minacciato, l'istrice è amichevole e pacifico. Se l'animale si sente attaccato, si difende con veemenza e ostinazione. L'istrice è tranquillo, mite e un buon insegnante. Pur facendo a volte un'impressione lenta, questo roditore è in grado di reagire molto rapidamente.",
"stekelstaarteekhoorn": "Lo scoiattolo spinoso vive sugli alberi alti dove si muove velocemente, agilmente e con grandi salti. Questo piccolo roditore sa nascondersi molto bene quando si avvicina il pericolo: anche un grande gruppo è appena percettibile. Lo scoiattolo spinoso è pacifico, un po' nervoso di tanto in tanto, vivace e birichino. Questo animale è sensibile e ha sensi molto sviluppati.",
"stokstaartje": "Questo energetico scavatore costruisce un complesso sistema di gallerie. Il suricato è molto sociale e spesso affettuoso. Questo animale si trova a suo agio ovunque con una facilità sorprendente. Il suricato agisce raramente d'istinto: impara molto dall'esperienza. Ha una buona memoria ed è molto perspicace. Il suricato è socievole, amichevole, divertente e giocoso, ma sempre vigile e straordinariamente coraggioso. I suricati amano stare al sole, ma possono anche diventare improvvisamente impetuosi e indaffarati in qualcosa.",
"struisvogel": "Lo struzzo è il più veloce degli uccelli corridori del mondo. Sono forti, si muovono con fluidità e hanno una grande resistenza. Questi uccelli sono molto attenti. Lo struzzo è tollerante verso altre specie animali e collabora bene in gruppo. Questo animale è un gaudente. In caso di conflitto, lo struzzo può essere un temibile avversario.",
"tapir": "Il tapiro è un animale bonario che vive nelle foreste tropicali e nei pascoli. Sono vigili ma anche di natura tranquilla. Sono veri animali abitudinari che percorrono sempre gli stessi sentieri. Sono curiosi ma anche piuttosto timidi. Sono pacifici e amano la loro dimora fissa.",
"tijger": "Questo magnifico felino unisce in sé una bellezza seducente e una selvaggia indomabilità. Le tigri sono ben consapevoli della loro forza. Amano vivere e lavorare da sole, ma sentono comunque molto bene i propri simili. La tigre è amichevole e condivide il cibo con gli altri quando ne ha troppo. Questo felino evita i conflitti fisici con i propri simili e cerca altre soluzioni. La tigre è coraggiosa.",
"uil": "Il gufo è un cacciatore potente e attivo che si avventura di notte. Hanno orecchie e occhi molto sviluppati. Il gufo è attento: in ogni momento osserva l'area circostante. Il gufo è molto bravo a mimetizzarsi. Questo uccello notturno è silenzioso, pulito e utile. Il gufo è coraggioso e abile. Aiutano i simili più deboli.",
"vleermuis": "Questo animale notturno ha un senso unico e molto sviluppato con l'ecolocalizzazione. Il pipistrello è un animale molto utile. Vive in grandi gruppi e si prende cura dei piccoli. Il pipistrello è molto vivace e un volatore molto agile. Il pipistrello è un cacciatore unico ed è molto attento.",
"vos": "La volpe è un predatore snello ed elegante. Questo animale percepisce il pericolo, ma non lo teme. Sono audaci e astuti. La volpe è intelligente e ingegnosa. È un opportunista. La volpe è in grado di adattarsi costantemente a nuove situazioni e ha un grande istinto di sopravvivenza.",
"walrus": "Questo grande, forte e imponente mammifero marino con lunghe zanne vive nelle regioni polari. Il tricheco è un animale sociale diurno e molto socievole. Preferisce i grandi gruppi, ama stare vicino agli altri e ha pochi nemici. Il tricheco è un gaudente e sensibile.",
"wezel": "Questo mustelide è il più piccolo mammifero predatore del mondo. La donnola è audace, coraggiosa, straordinariamente agile e muscolosa. Questo animale attacca a volte prede molte volte più grandi di sé. La donnola è previdente e caccia a volte più animali del necessario, conservandoli poi come scorta. La donnola è orientata alla famiglia e amante della libertà.",
"wilde-eend": "Il germano reale vive in stagni, paludi, laghi e fossati. Questo uccello acquatico mangia piccoli pesci, lumache e vermi, ma è molto flessibile nella scelta del cibo. Il germano reale è sociale, socievole, tollerante e molto accomodante. Ha una grande capacità di adattamento. Questo animale è attivo, vivace e prudente.",
"wolf": "I branchi di questo canide sociale sono strettamente organizzati. Comunica intensamente con il suo caratteristico ululato, almeno quando il legame sociale è forte. Il lupo è abile, astuto e ingegnoso. Agisce fedelmente verso i propri simili e dà importanza a una buona vita comunitaria. Il lupo ha una grande resistenza. Si adatta rapidamente a nuove situazioni.",
"zebra": "Questo animale molto sociale vive nelle vaste pianure erbose. La zebra è vivace, forte e attiva per tutta la giornata. L'animale è sveglio, amichevole e ha una grande resistenza. La zebra vive in gruppi familiari con una rigida gerarchia e ha un legame familiare forte e duraturo. La zebra si prende grande cura dei membri della famiglia più giovani, anziani e più deboli.",
"zeehond": "La foca è un piccolo predatore acquatico. Questo agile nuotatore e sommozzatore esce dall'acqua solo per riposare o prendere il sole. Vivono in piccoli branchi e sono sociali. La foca è curiosa di imparare, laboriosa e vivace. L'animale è amichevole, ma può rispondere prontamente.",
"zeeschildpad": "Con il loro guscio aerodinamico, le potenti tartarughe marine si muovono nell'acqua ad alta velocità. Questo viaggiatore unico percorre grandi distanze e ha una grande resistenza. La tartaruga marina è sempre in movimento e raramente smette di nuotare. Questo animale acquatico è amichevole, affascinante e ama tornare in un posto familiare.",
"zwaan": "Il cigno è un grande, maestoso ed elegante uccello acquatico. È intelligente e rapido di comprensione. Il cigno mostra sicurezza in sé, ma non la esprime e preferisce la tranquillità. Il cigno ha una grande capacità di adattamento. Questo uccello acquatico è fedele e tenero con i piccoli. Il cigno difende la prole con veemenza, ma reagirà violentemente solo se sfidato.",
}

def main():
    with open(DATA_FILE, encoding="utf-8") as f:
        animals = json.load(f)

    updated = 0
    for a in animals:
        slug = a["slug"]
        if slug in TRANSLATIONS:
            a["desc_it"] = TRANSLATIONS[slug]
            updated += 1

    with open(DATA_FILE, "w", encoding="utf-8") as f:
        json.dump(animals, f, ensure_ascii=False, indent=2)

    print(f"Updated desc_it for {updated} animals.")
    no_desc = [a["nl"] for a in animals if not a.get("desc_it")]
    if no_desc:
        print(f"Still missing desc_it: {no_desc}")

if __name__ == "__main__":
    main()
