#!/usr/bin/env python3
"""Apply Italian names to new animals."""
import json
from pathlib import Path

ROOT = Path(__file__).parent.parent
DATA_FILE = ROOT / "data" / "animals.json"

IT_NAMES = {
"buizerd": "Poiana",
"bultrug": "Megattera",
"caracara": "Caracara",
"cavia": "Cavia",
"chinchilla": "Cincillà",
"cichlide": "Ciclide",
"civetkat": "Zibetto africano",
"cobra": "Cobra",
"comorenwever": "Tessitore delle Comore",
"coscoroba": "Cigno coscoroba",
"coyote": "Coyote",
"dagpauwoog": "Occhio di pavone",
"damhert": "Daino",
"danio": "Danio",
"das": "Tasso",
"dikdik": "Dik-dik",
"dikhoornschaap": "Pecora delle Montagne Rocciose",
"diksnavelmees": "Cincia dal becco spesso",
"distelvink": "Cardellino",
"doornkruiper": "Rampichino",
"doornsnavel": "Becco spinoso",
"draaihals": "Torcicollo",
"drongo": "Drongo",
"dwerghert": "Cervo pigmeo",
"dwergmuis": "Topolino delle spighe",
"dziggetai": "Dziggetai",
"edelhert": "Cervo nobile",
"eidereend": "Edredone",
"eland": "Alce",
"ever": "Cinghiale",
"fazant": "Fagiano",
"fitis": "Luì grosso",
"fluithaas": "Pika",
"forel": "Trota",
"franjeaap": "Saki frangiato",
"franjepoot": "Falaropo",
"franjeschildpad": "Tartaruga frangiata",
"frankolijn": "Francolino",
"franse-bulldog": "Bulldog francese",
"fregatvogel": "Fregata",
"fret": "Furetto",
"fuut": "Svasso maggiore",
"fuutkoet": "Tuffetto",
"gaai": "Ghiandaia",
"gaffelbok": "Antilocapra",
"galago": "Galagone",
"gaur": "Gaur",
"gaviaal": "Gaviale",
"geep": "Geep",
"geit": "Capra",
"gekko": "Geco",
"gems": "Camoscio",
"genetkat": "Genetta",
"gibbon": "Gibbonw",
"goendi": "Goundi",
"golden-retriever": "Golden retriever",
"goudhaan": "Regolo",
"goudplevier": "Piviere dorato",
"goudvink": "Ciuffolotto",
"goudvis": "Pesce rosso",
"grauwe-gans": "Oca selvatica",
"griel": "Occhione",
"griend": "Globicefalo",
"grijs-bokje": "Antilope grigia",
"groenling": "Verdone",
"grondeekhoorn": "Scoiattolo terragnolo",
"grondel": "Ghiozzo",
"guppy": "Guppy",
"haan": "Gallo",
"haas": "Lepre",
"hagedis": "Lucertola",
"hazelmuis": "Moscardino",
"hazewind": "Levriero",
"herdershond": "Cane da pastore",
"hert": "Cervo",
"hoenderkoet": "Gallina sultana",
"hokko": "Hokko",
"hond": "Cane",
"hondshaai": "Gattuccio",
"hop": "Upupa",
"houtduif": "Colombaccio",
"ibis": "Ibis",
"ijsduiker": "Strolaga maggiore",
"ijsvogel": "Martin pescatore",
"jabiroe": "Jabiru",
"jacana": "Jacana",
"jachtluipaard": "Ghepardo",
"jaguarundi": "Giaguarundi",
"jak": "Yak",
"jako": "Pappagallo cenerino",
"jan-van-gent": "Sula",
"kaaiman": "Caimano",
"kabeljauw": "Merluzzo",
"kaketoe": "Cacatua",
"kameel": "Cammello",
"kamsalamander": "Tritone crestato",
"kanarie": "Canarino",
"kapucijnaap": "Scimmia cappuccino",
"karakol": "Caracal",
"karekiet": "Cannaiola",
"katfret": "Gatto selvatico asiatico",
"kauw": "Taccola",
"kea": "Kea",
"kemphaan": "Combattente",
"kempvis": "Betta splendente",
"kever": "Coleottero",
"kievit": "Pavoncella",
"kikker": "Rana",
"klauwier": "Averla",
"klipdas": "Damano",
"kluut": "Avocetta",
"knobbelzwijn": "Facocero",
"koedoe": "Kudu",
"koekoek": "Cuculo",
"kogelvis": "Pesce palla",
"koi": "Carpa koi",
"kokako": "Kokako",
"kolibrie": "Colibrì",
"kongoni": "Kongoni",
"konijn": "Coniglio",
"kookaburra": "Kookaburra",
"koolmees": "Cinciallegra",
"koraalduivel": "Pesce leone",
"koraalvlinder": "Pesce farfalla",
"kraai": "Cornacchia",
"krab": "Granchio",
"kreeft": "Aragosta",
"krekel": "Grillo",
"kwartel": "Quaglia",
"kwartelsnip": "Frullino",
"kwikstaart": "Ballerina",
"lama": "Lama",
"lampongaap": "Macaco di Lampung",
"leeuwaapje": "Tamarino leone",
"leeuwerik": "Allodola",
"lepelaar": "Spatola",
"libel": "Libellula",
"lieveheersbeestje": "Coccinella",
"lijster": "Tordo",
"linsang": "Linsang",
"loodsmannetje": "Pesce pilota",
"lori-aap": "Lori lento",
"lori-papegaai": "Lorìchetto",
"makreelhaai": "Squalo mako",
"maleise-beer": "Orso malese",
"mamba": "Mamba",
"mandril": "Mandrillo",
"manenwolf": "Lupo dalla criniera",
"mangoest": "Mangusta",
"manoel": "Manoel",
"manta": "Manta",
"mara": "Mara",
"maraboe": "Marabù",
"margay": "Margay",
"marlijn": "Marlin",
"marmersalamander": "Salamandra marmorizzata",
"marmot": "Marmotta",
"marter": "Martora",
"maskerwimpelvis": "Pesce bandiera mascherato",
"meerkat": "Cercopiteco",
"meerkoet": "Folaga",
"meerval": "Siluro",
"meeuw": "Gabbiano",
"merel": "Merlo",
"mier": "Formica",
"monniksrob": "Foca monaca",
"muis": "Topo",
"murene": "Murena",
"mus": "Passero",
"mustang": "Mustang",
"nachtaap": "Scimmia notturna",
"nachtegaal": "Usignolo",
"nandoe": "Nandù",
"narwal": "Narvalo",
"neusbeer": "Coati",
"newfoundlander": "Terranova",
"oeakari": "Uacari",
"opossum": "Opossum",
"oranje-passiebloemvlinder": "Farfalla della passiflora",
"oribi": "Oribi",
"orka": "Orca",
"ornaatelfje": "Elfo ornato",
"oropendola": "Oropendola",
"paard": "Cavallo",
"paca": "Paca",
"pad": "Rospo",
"pademelon": "Pademelon",
"paling": "Anguilla",
"palmtortel": "Tortora palmista",
"papegaai": "Pappagallo",
"papegaaivis": "Pesce pappagallo",
"paradijsvogel": "Uccello del paradiso",
"pardelkat": "Gatto leopardo",
"parelhoen": "Faraona",
"parelkwal": "Medusa perlata",
"parkiet": "Parrocchetto",
"patrijs": "Pernice",
"pauwoogstekelrog": "Razza occhio di pavone",
"pekari": "Pecari",
"pelikaan": "Pellicano",
"penseelaapje": "Uistitì",
"penseelkrab": "Granchio decoratore",
"pijlinktvis": "Calamaro",
"pimpelmees": "Cinciarella",
"pinguin": "Pinguino",
"piranha": "Piranha",
"plevier": "Piviere",
"poedel": "Barboncino",
"pony": "Pony",
"poolvos": "Volpe artica",
"potto": "Potto",
"prairiehond": "Cane della prateria",
"ree": "Capriolo",
"renvogel": "Uccello corridore",
"ringstaartmaki": "Lemure dalla coda inanellata",
"rivierdolfijn": "Delfino di fiume",
"rode-lynx": "Lince rossa",
"roek": "Corvo comune",
"roerdomp": "Tarabuso",
"roodborstje": "Pettirosso",
"saiga": "Saiga",
"saki": "Saki",
"salangaan": "Rondone nidificante",
"saterhoen": "Gallina satiro",
"schaap": "Pecora",
"schaarbek": "Beccapesci",
"schippertje": "Esperide",
"scholekster": "Beccaccia di mare",
"schorpioen": "Scorpione",
"schrijvertje": "Girinide",
"schroefhoorngeit": "Markhor",
"secretarisvogel": "Uccello segretario",
"seriema": "Seriema",
"serval": "Serval",
"sijs": "Lucherino",
"sikahert": "Cervo sika",
"sint-bernard": "San Bernardo",
"slaapmuis": "Ghiro",
"slangehalsvogel": "Aninga",
"slankbeer": "Orso labiato",
"slechtvalk": "Falco pellegrino",
"smelleken": "Smeriglio",
"sneeuwhoen": "Pernice bianca",
"sneeuwstormvogel": "Procellaria delle nevi",
"sneeuwuil": "Gufo delle nevi",
"snip": "Beccaccino",
"snoek": "Luccio",
"specht": "Picchio",
"spiesbok": "Orice",
"spinaap": "Scimmia ragno",
"spitsmuis": "Toporagno",
"spitssnuitdolfijn": "Delfino comune",
"spitsvogel": "Averla capirossa",
"spoorkoekoek": "Cuculo speronato",
"spotlijster": "Mimo",
"spreeuw": "Storno",
"springhaas": "Lepre saltante",
"sprinkhaan": "Cavalletta",
"staartmees": "Codibugnolo",
"steenarend": "Aquila reale",
"steenbok": "Stambecco",
"steenloper": "Voltapietre",
"stekelstaarteend": "Anatra codaspinosa",
"stekelstaartzwaluw": "Rondone codaspinosa",
"steltkluut": "Cavaliere d'Italia",
"steltral": "Ral trampoliere",
"steppelemming": "Lemming della steppa",
"stern": "Sterna",
"steur": "Storione",
"stormvogel": "Uccello delle tempeste",
"strandloper": "Gambecchio",
"streepmuis": "Topo striato",
"tagoean": "Tagouan",
"taipan": "Taipan",
"tarpon": "Tarpone",
"termiet": "Termite",
"tijgerhaai": "Squalo tigre",
"tjiftjaf": "Luì piccolo",
"toekan": "Tucano",
"toepaja": "Tupaio",
"toerako": "Turaco",
"torenvalk": "Gheppio",
"vampierinktvis": "Calamaro vampiro",
"veldmuis": "Arvicola",
"vink": "Fringuello",
"vlinder": "Farfalla",
"vogelbekdier": "Ornitorinco",
"vuursalamander": "Salamandra pezzata",
"vuurstaartlabeo": "Labeo dalla coda rossa",
"wasbeer": "Procione",
"wever": "Tessitore",
"wielewaal": "Rigogolo",
"winterkoninkje": "Scricciolo",
"wombat": "Vombato",
"wouw": "Nibbio",
"wulk": "Buccino",
"wulp": "Chiurlo",
"zalm": "Salmone",
"zebramangoest": "Mangusta bandita",
"zee-egel": "Riccio di mare",
"zee-engel": "Squalo angelo",
"zeeduivel": "Rana pescatrice",
"zeekat": "Seppia",
"zeeleeuw": "Leone marino",
"zeepaardje": "Cavalluccio marino",
"zeester": "Stella marina",
"zeewolf": "Pesce lupo",
"zonnebaars": "Persico sole",
"zonnevis": "Pesce luna",
"zwaardvis": "Pesce spada",
"zwaluw": "Rondine",
}

def main():
    with open(DATA_FILE, encoding="utf-8") as f:
        animals = json.load(f)

    updated = 0
    for a in animals:
        if not a.get("it") and a["slug"] in IT_NAMES:
            a["it"] = IT_NAMES[a["slug"]]
            updated += 1

    # Fix gibbon typo
    for a in animals:
        if a["slug"] == "gibbon":
            a["it"] = "Gibbonw".replace("w", "")

    # Fix honingdas: "Ratel" (Afrikaans) → proper Italian name
    for a in animals:
        if a["slug"] == "honingdas":
            a["it"] = "Tasso del miele"

    with open(DATA_FILE, "w", encoding="utf-8") as f:
        json.dump(animals, f, ensure_ascii=False, indent=2)

    still_missing = [a["slug"] for a in animals if not a.get("it")]
    print(f"Applied Italian names to {updated} animals.")
    if still_missing:
        print(f"Still missing: {still_missing}")

if __name__ == "__main__":
    main()
